Explictly close file handles.
Try to ensure file handles are closed sooner in frequently run code.
Without this errors like
IOError: [Errno 24] Too many open files: '5.2/binutils-2.24/ld/scripttempl/armaout.sc'
occur when running slic under PyPy because PyPy garbage collects the
file handles later than regular CPython (see
https://bitbucket.org/pypy/pypy/issues/878/too-many-open-files ).